name: Build dummy-app-2

on:
  push:
    branches:
      - main
    paths:
      - apps/dummy-app-2/frontend/my-app/**
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-frontend-build.yml
    with:
      app_name: dummy-app-2
      app_path: apps/dummy-app-2/frontend/my-app
      bump_type: patch
      node_version: "20"
      build_command: npm run build
      output_dir: build
    secrets:
      REACT_APP_API_BASE: ${{ secrets.REACT_APP_API_BASE }}
