name: Build my-app

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - apps/crud-app/frontend/my-app/**

jobs:
  build:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-frontend-build.yml
    with:
      app_name: my-app
      app_path: apps/crud-app/frontend/my-app
      node_version: "20"
      build_command: npm run build
      output_dir: build
    secrets:
      REACT_APP_API_BASE: ${{ secrets.REACT_APP_API_BASE }}
